language: node_js
node_js:
  - "8"
addons:
  chrome: stable
sudo: required
before_script:
  - "sudo chown root /apt/google/chrome/chrome-sandbox"
  - "sudo chown 4755 /apt/google/chrome/chrome-sandbox"